#pragma once


#define IDR_APPLICATION_MANIFEST 1
#define IDR_VERSION_INFORMATION 1

#define IDR_STARTUP_CHECK_HTML 1000
#define IDR_APPLICATION_CSS 1001
#define IDR_APPLICATION_JAVASCRIPT 1002
#define IDR_APPLICATION_HTML 1003
#define IDR_APPLICATION_LOGO 1004

